on:
  pull_request:
    branches: [ gh-pages ]
    types: [ closed ]
    
name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","HelpersMG","readr"))'
        
      - uses: r-lib/actions/setup-tinytex@v1
      - name : install tinytex
        run: tlmgr --version
    
      - name: Render Book
        run: |
             Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook", output_dir="docs")'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/
          
# deploy to gh pages yml
  build-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
        
      - name: Download Artifacts üîª # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: docs
          
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs
          TARGET_FOLDER: docs # The folder the action should deploy.
          CLEAN: true
          PRESERVE: true
      
